import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { User } from '../auth/user.entity';

/**
 * Item Entity
 * Represents a resource/item owned by a user
 * Implements ownership-based access control
 */
@Entity()
export class Item {
  /**
   * Unique identifier for the item
   * Auto-generated by the database
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * Title of the item
   * Required field
   */
  @Column()
  title: string;

  /**
   * Optional description of the item
   * Can be null or undefined
   */
  @Column({ nullable: true })
  description?: string;

  /**
   * Reference to the User who owns this item
   * Many items can belong to one user (Many-to-One relationship)
   * Used for authorization checks on update/delete operations
   */
  @ManyToOne(() => User)
  owner: User;
}
