import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/**
 * User Entity
 * Represents a user in the system with authentication credentials
 */
@Entity()
export class User {
  /**
   * Unique identifier for the user
   * Auto-generated by the database
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * User's email address
   * Must be unique across all users
   * Used for authentication
   */
  @Column({ unique: true })
  email: string;

  /**
   * Hashed password using bcrypt
   * Never store plain text passwords!
   */
  @Column()
  passwordHash: string;
}
